### PR TITLE
Feature/organizerture

### PR DESCRIPTION
**Pull request by Afaed**

### CODE REVIEW

**Review by Naomilounsbury — CHANGES_REQUESTED** [review]
7 files changed, I can't

**Comment by jdpasternak** [comment]
This looks to be the same changed as #91. Please review the comments made there and apply the appropriate changes

**Review by jdpasternak — CHANGES_REQUESTED** [review]
Please review comments from #91

**Comment by jdpasternak** [comment]
This will not be approved as it's out of scope

**Pull request closed without merging**
